name: Structurizr Export Action
description: Exports Structurizr diagrams to PNG or SVG using Puppeteer. Depends on Structurizr Lite configured in the workflow.
author: 'Vitor Martins de SantAnna'

inputs:
  structurizr_url:
    description: 'URL of the workspace in Structurizr (default: http://localhost:8080/workspace/diagrams)'
    required: true
  format:
    description: 'Output format of the diagrams (png or svg)'
    required: true
  output_dir:
    description: 'Output directory for the diagrams'
    required: true
runs:
  using: 'node16'
  pre: |
    echo "Listing current directory contents:"
    ls -la
    echo "Listing parent directory contents:"
    ls -la ..
    echo "Listing home directory contents:"
    ls -la /home/runner
    echo "Listing Action-specific folder contents:"
    ls -la /home/runner/work/_actions
  main: 'export-diagrams.js'
  main: 'export-diagrams.js'
branding:
  icon: "upload-cloud"
  color: "blue"