name: Structurizr Export Action
description: Exports Structurizr diagrams to PNG or SVG using Puppeteer. Depends on Structurizr Lite configured in the workflow.
author: 'Vitor Martins de SantAnna'

inputs:
  structurizrUrl:
    description: 'URL of the workspace in Structurizr (default: http://localhost:8080/workspace/diagrams)'
    required: true
  format:
    description: 'Output format of the diagrams (png or svg)'
    required: true
  outputDir:
    description: 'Output directory for the diagrams'
    required: true
runs:
  using: 'node16'
  main: 'export-diagrams.js'
  pre: |
    npm install
branding:
  icon: "upload-cloud"
  color: "blue"