name: Structurizr Export Action
description: Exporta diagramas Structurizr para PNG usando Puppeteer. Depende do Structurizr Lite configurado no workflow.
author: 'Vitor Martins de SantAnna'

inputs:
  structurizrUrl:
    description: 'URL do workspace no Structurizr (padrão: http://localhost:8080/workspace/diagrams)'
    required: true
  format:
    description: 'Formato de saída dos diagramas (png ou svg)'
    required: true
  outputDir:
    description: 'Diretório de saída dos diagramas'
    required: true
runs:
  using: 'node16'
  main: 'export-diagrams.js'
branding:
  icon: "upload-cloud"
  color: "blue"